### ISSUE TITLE
Connection Schema 

### ISSUE THREAD

**Issue by ortegafernando** [PurpleAlien/jk-bms_grafana#1]
Hi, could you add a connection schema? RS485 converter? directly a RS232 converter? Thanks,

**Comment by PurpleAlien** [comment]
Actually, I have to revise the whole thing since more recent versions of the BMS use a different protocol. I'll work on it as soon as I have one of those, but it's not really a priority at the moment.

**Comment by PurpleAlien** [comment]
I've updated the code and also provided some information on how to connect it in the readme.
